language: cpp
compiler: gcc
sudo: required
dist: trusty

env:
  - BUILD_TYPE=Debug FIREPONY_GPU_ARCHITECTURE=sm_35
  - BUILD_TYPE=Release FIREPONY_GPU_ARCHITECTURE=sm_52

before_install:
  - git submodule update --init --recursive
  - travis_retry sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - travis_retry wget -nv "http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.0-28_amd64.deb"
  - sudo dpkg -i cuda-repo-ubuntu1404_7.0-28_amd64.deb
  - travis_retry sudo apt-get update -qq

install:
  - travis_retry sudo apt-get install -qq -y gcc-4.9 g++-4.9 cmake git cuda-toolkit-7-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20

script:
  - mkdir build
  - pushd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - travis_wait make -j2
  - popd

